# Generated by Django 5.0.2 on 2024-02-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldtester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zonecontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('rclass', models.CharField(max_length=10)),
                ('ttl', models.IntegerField(default=0)),
                ('data', models.CharField(max_length=1000)),
            ],
        ),
    ]
