# Generated by Django 5.0.2 on 2024-02-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldtester', '0002_zonecontent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zonecontent',
            index=models.Index(fields=['name'], name='tldtester_z_name_83c518_idx'),
        ),
    ]
