# Generated by Django 5.0.2 on 2024-02-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldtester', '0003_zonecontent_tldtester_z_name_83c518_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonecontent',
            name='lastEdition',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
