# Generated by Django 5.0.2 on 2024-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldtester', '0004_zonecontent_lastedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonecontent',
            name='ttl',
            field=models.CharField(max_length=5),
        ),
    ]
